### ISSUE TITLE
Add ability to pass string of html to mail interface

### ISSUE THREAD

**Issue by mitchdennett** [severell/severell#3]
Add a new method called `html(String html)` to mail interface.

We currently let people pass a template to an email but we need the ability to pass a string of html.

- Add html method that takes a string and returns Mail interface. (com.severell.core.mail.Mail.java)

- Make sure the SMTP driver and Log driver implement this new function (com.severell.core.mail.MailSMTPDriver.java, (com.severell.core.mail.MailLogDriver.java))

- Add test for this new function

**Comment by naruto678** [comment]
@mitchdennett  can this be assigned to me as a part of hacktoberfest?

**Comment by mitchdennett** [comment]
Absolutely! I'll assign it to you

**Comment by naruto678** [comment]
@mitchdennett  I will get started on this. Thanks a lot

**Comment by mitchdennett** [comment]
feel free to join our discord channel https://discord.gg/69JRdug. I'm on there all the time if you need any help

**Comment by naruto678** [comment]
@mitchdennett the invite says it is expired.

**Comment by mitchdennett** [comment]
@naruto678 https://discord.gg/KAjfBWv. Sorry try this one

**Comment by sumanth-thyagarajan** [comment]
@mitchdennett can I work on this issue

**Comment by mitchdennett** [comment]
@sumanth-thyagarajan I believe @naruto678 is currently working on this one

**Comment by mitchdennett** [comment]
@naruto678 How's it going on this issue? If you need any help don't hesitate to reach out.

**Comment by mitchdennett** [comment]
@Belovedbb
